name: Backend Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: linting
        run:  |
          cd starter/backend
          python -m pip install --upgrade pip
          pip install pipenv
          pip install flake8
          pipenv install
          pipenv run lint
      - name: testing
        run:  |
          cd starter/backend
          pipenv run test
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Amazon ECR "Login" Action for GitHub Actions
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1
      - name: Build, tag, and push docker image to Amazon ECR
        run: |
          cd starter/backend
          docker build --tag 833847858982.dkr.ecr.us-east-1.amazonaws.com/backend .
          docker push 833847858982.dkr.ecr.us-east-1.amazonaws.com/backend
      - name: Update the Kubeconfig
        run: aws eks --region us-east-1 update-kubeconfig --name cluster
      - name: Deploy to EKS
        run: |
            cd starter/backend
            kustomize edit set image backend=833847858982.dkr.ecr.us-east-1.amazonaws.com/backend
            kustomize build | kubectl apply -f -