name: Backend Continuous Integration

on:
  workflow_dispatch:

  pull_request:
    branches: 
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: linting
        run:  |
          cd starter/backend
          python -m pip install --upgrade pip
          pip install pipenv
          pip install flake8
          pipenv install
          pipenv run lint

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: linting
        run:  |
          cd starter/backend
          python -m pip install --upgrade pip
          pip install pipenv
          pip install flake8
          pipenv install
          pipenv run test

  building:
    needs: [linting, testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: building
        run:  |
          cd starter/backend
          docker build --tag mp-backend:latest .